# Disable Spring Boot's autoconfigured MongoDB tracing
management.metrics.mongo.command.enabled=false
management.tracing.enabled=false
# Configuracion para que los JSPs tengna soporte en Spring Boot
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

# Credenciales para conectarse a MongoDB
spring.config.import=mongodb.properties