# Disable Spring Boot's autoconfigured MongoDB tracing
management.metrics.mongodb.command.enabled=false
management.tracing.enabled=false

# Credenciales para conectarse a MongoDB
spring.config.import=mongodb.properties