# Durante desarrollo; desactivar cuando se entregue
#spring.thymeleaf.cache=false
# Disable Spring Boot's autoconfigured MongoDB tracing
management.metrics.mongo.command.enabled=false
management.tracing.enabled=false
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

